package dev.slne.surf.rabbitmq.api

import dev.slne.surf.api.core.serializer.SurfSerializerModule
import dev.slne.surf.api.core.util.logger
import dev.slne.surf.rabbitmq.api.connection.RabbitMQConnection
import dev.slne.surf.rabbitmq.api.exception.SurfRabbitApiAlreadyFrozenException
import dev.slne.surf.rabbitmq.api.exception.SurfRabbitApiNotFrozenException
import dev.slne.surf.rabbitmq.api.internal.RabbitMQConfig
import dev.slne.surf.rabbitmq.api.packet.standard.response.StringResponsePacket
import dev.slne.surf.rabbitmq.api.packet.standard.response.optional.OptionalStringResponsePacket
import dev.slne.surf.rabbitmq.api.packet.standard.response.primitive.OptionalPrimitiveResponse
import dev.slne.surf.rabbitmq.api.packet.standard.response.primitive.PrimitiveResponse
import dev.slne.surf.rabbitmq.api.packet.standard.response.primitive.array.ArrayResponse
import dev.slne.surf.rabbitmq.api.packet.standard.response.primitive.array.OptionalArrayResponse
import dev.slne.surf.rabbitmq.api.rpc.RabbitRpcServiceFactory
import dev.slne.surf.rabbitmq.api.rpc.descriptor.RabbitRpcServiceDescriptor
import kotlinx.coroutines.*
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.cbor.Cbor
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.contextual
import kotlinx.serialization.modules.overwriteWith
import org.jetbrains.annotations.MustBeInvokedByOverriders
import kotlin.reflect.KClass

@OptIn(ExperimentalSerializationApi::class)
abstract class RabbitMQApi @InternalRabbitMQ constructor(
    @InternalRabbitMQ val config: RabbitMQConfig,
    @InternalRabbitMQ val pluginName: String,
    val cbor: Cbor
) {
    @InternalRabbitMQ
    val scope =
        CoroutineScope(Dispatchers.Default + CoroutineName("RabbitMQApi-$pluginName") + SupervisorJob() + CoroutineExceptionHandler { context, throwable ->
            log.atSevere()
                .withCause(throwable)
                .log("Unhandled exception in RabbitMQApi coroutine ${context[CoroutineName]}")
        })

    @InternalRabbitMQ
    open val rpcService = RabbitRpcServiceFactory.instance.createRpcService(this)

    open val connection = RabbitMQConnection.create(this)

    private var frozen = false

    @MustBeInvokedByOverriders
    open suspend fun connect() {
        if (!isFrozen()) throw SurfRabbitApiNotFrozenException()

        connection.connect()
    }

    suspend fun freezeAndConnect() {
        freeze()
        connect()
    }

    @MustBeInvokedByOverriders
    open suspend fun disconnect() {
        connection.disconnect()

        scope.cancel("RabbitMQApi disconnected")
    }

    fun freeze() {
        if (isFrozen()) throw SurfRabbitApiAlreadyFrozenException()
        frozen = true
    }

    fun isFrozen(): Boolean = frozen

    /**
     * Returns the generated RPC service descriptor for the given service interface.
     *
     * This is an advanced API. Most users should use
     * `ClientRabbitMQApi.createRpcService` on the client and
     * `ServerRabbitMQApi.registerRpcService` on the server instead.
     *
     * The descriptor contains metadata generated by the Surf RabbitMQ KSP processor,
     * including the service name, callable RPC methods, parameter metadata, return
     * types, and serializers. It is used internally to create client proxies and to
     * dispatch server-side RPC calls.
     *
     * Example:
     *
     * ```kotlin
     * val descriptor = api.serviceDescriptorOf<UserService>()
     * println(descriptor.fqName)
     * ```
     *
     * @param Service the RPC service interface type.
     * @return the generated descriptor for [Service].
     * @throws IllegalStateException if no generated descriptor for [Service] can be found.
     */
    inline fun <reified Service : Any> serviceDescriptorOf(): RabbitRpcServiceDescriptor<Service> {
        return serviceDescriptorOf(Service::class)
    }

    /**
     * Returns the generated RPC service descriptor for the given service interface.
     *
     * Use this overload when the service type is only available as a [KClass]. For
     * normal Kotlin call sites, prefer the reified `serviceDescriptorOf<Service>()`
     * overload.
     *
     * This is an advanced API. Most users should use
     * `ClientRabbitMQApi.createRpcService` on the client and
     * `ServerRabbitMQApi.registerRpcService` on the server instead.
     *
     * @param serviceKClass the RPC service interface class.
     * @return the generated descriptor for [serviceKClass].
     * @throws IllegalStateException if no generated descriptor for [serviceKClass] can be found.
     */
    fun <Service : Any> serviceDescriptorOf(serviceKClass: KClass<Service>): RabbitRpcServiceDescriptor<Service> {
        return rpcService.serviceDescriptorOf(serviceKClass)
    }

    companion object {
        private val log = logger()

        @InternalRabbitMQ
        fun createCbor(additionalSerializerModule: SerializersModule): Cbor = Cbor {
            ignoreUnknownKeys = true
            serializersModule = SerializersModule {
                include(SurfSerializerModule.all.overwriteWith(additionalSerializerModule))
                include(defaultSerializersModule)
            }
        }

        private val defaultSerializersModule = SerializersModule {
            include(PrimitiveResponse.SERIALIZER_MODULE)
            include(OptionalPrimitiveResponse.SERIALIZER_MODULE)
            include(ArrayResponse.SERIALIZER_MODULE)
            include(OptionalArrayResponse.SERIALIZER_MODULE)

            contextual(StringResponsePacket.serializer())
            contextual(OptionalStringResponsePacket.serializer())
        }
    }
}