package dev.slne.surf.eventbus.ksp.processor.query.codegen

import com.google.devtools.ksp.processing.CodeGenerator
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.addOriginatingKSFile
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import dev.slne.surf.eventbus.ksp.processor.query.ClassNames
import dev.slne.surf.eventbus.ksp.processor.query.MemberNames
import dev.slne.surf.eventbus.ksp.processor.query.Types
import dev.slne.surf.eventbus.ksp.processor.query.model.QueryFunctionModel
import dev.slne.surf.eventbus.ksp.processor.query.model.QueryServiceModel

/** Generates `<Name>Descriptor` (callables + invokers) and `<Name>ClientImpl` (the query proxy). */
class QueryDescriptorCodegen(private val codeGenerator: CodeGenerator) {

    private companion object {
        const val INSTANCE_ID_NAME = "__instanceId__"
        const val JSON_NAME = "__json__"
        const val TRANSPORT_NAME = "__transport__"
        const val DESCRIPTOR_NAME = "__descriptor__"
        const val SERIALIZER_CACHE_NAME = "__serializerCache__"
        const val EMPTY_ARRAY_NAME = "__emptyArray__"
    }

    fun generate(service: QueryServiceModel) {
        val descriptorType = TypeSpec.objectBuilder(service.descriptorClassName)
            .addOriginatingKSFile(service.containingFile)
            .addAnnotation(optIn())
            .addModifiers(KModifier.INTERNAL)
            .addSuperinterface(ClassNames.queryServiceDescriptor.parameterizedBy(service.serviceClassName))
            .addProperty(
                PropertySpec.builder("simpleName", String::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%S", service.simpleName)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("fqName", String::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%S", service.fqName)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("timeoutMillis", Long::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%LL", service.timeoutMillis)
                    .build()
            )
            .apply {
                service.functions.forEach { function ->
                    addProperty(createInvokerProperty(service, function))
                }
                addProperty(createCallablesProperty(service))
            }
            .addFunction(createGetCallableFunction(service))
            .addFunction(createCreateInstanceFunction(service))
            .build()

        val clientType = createClientType(service)

        FileSpec.builder(service.packageName, "${service.simpleName}Descriptor")
            .addFileComment("Code generated by Surf EventBus. DO NOT EDIT!")
            .addAnnotation(optIn())
            .indent("    ")
            .addType(descriptorType)
            .addType(clientType)
            .build()
            .writeTo(codeGenerator, aggregating = false)
    }

    private fun optIn(): AnnotationSpec = AnnotationSpec.builder(ClassNames.optIn)
        .addMember("%T::class", ClassNames.internalEventBusApi)
        .build()

    private fun createInvokerProperty(service: QueryServiceModel, function: QueryFunctionModel): PropertySpec {
        val invokerType = ClassNames.queryInvoker.parameterizedBy(service.serviceClassName)

        val call = CodeBlock.builder()
            .add("service.%N(", function.name)
            .apply {
                function.parameters.forEachIndexed { index, parameter ->
                    if (index > 0) add(", ")
                    add("arguments[%L] as %T", index, parameter.type.toTypeName(function.typeParameterResolver))
                }
            }
            .add(")")
            .build()

        return PropertySpec.builder(function.invokerName, invokerType)
            .addModifiers(KModifier.PRIVATE)
            .initializer(
                CodeBlock.builder()
                    .add("%T { service, arguments -> %L }", ClassNames.queryInvoker, call)
                    .build()
            )
            .build()
    }

    private fun createCallablesProperty(service: QueryServiceModel): PropertySpec {
        val callablesType = MAP.parameterizedBy(
            String::class.asTypeName(),
            ClassNames.queryCallable.parameterizedBy(service.serviceClassName),
        )

        if (service.functions.isEmpty()) {
            return PropertySpec.builder("callables", callablesType)
                .addModifiers(KModifier.OVERRIDE)
                .initializer("%M()", MemberNames.emptyMap)
                .build()
        }

        val initializer = CodeBlock.builder()
            .add("%M(\n", MemberNames.mapOf)
            .withIndent {
                service.functions.forEachIndexed { index, function ->
                    if (index > 0) add(",\n")
                    add("%S to %L", function.name, createCallable(function))
                }
            }
            .add("\n)")
            .build()

        return PropertySpec.builder("callables", callablesType)
            .addModifiers(KModifier.OVERRIDE)
            .initializer(initializer)
            .build()
    }

    private fun createCallable(function: QueryFunctionModel): CodeBlock {
        return CodeBlock.builder()
            .add("%T(\n", ClassNames.queryCallableDefault)
            .withIndent {
                add("name = %S,\n", function.name)
                add(
                    "returnType = %T(%M<%T>(), %M()),\n",
                    ClassNames.queryTypeDefault,
                    MemberNames.kotlinTypeOf,
                    function.returnType.toTypeName(function.typeParameterResolver),
                    MemberNames.emptyList,
                )
                add("invoker = %N,\n", function.invokerName)
                add("parameters = %L,\n", createParametersArray(function))
            }
            .add(")")
            .build()
    }

    private fun createParametersArray(function: QueryFunctionModel): CodeBlock {
        if (function.parameters.isEmpty()) {
            return CodeBlock.of("%M()", MemberNames.emptyArray)
        }

        return CodeBlock.builder()
            .add("%M(\n", MemberNames.arrayOf)
            .withIndent {
                function.parameters.forEachIndexed { index, parameter ->
                    if (index > 0) add(",\n")
                    val name = parameter.name?.asString()
                        ?: error("Cannot generate function ${function.name}: parameter name is null")

                    add(
                        "%T(name = %S, type = %T(%M<%T>(), %M()), isOptional = %L, annotations = %M())",
                        ClassNames.queryParameterDefault,
                        name,
                        ClassNames.queryTypeDefault,
                        MemberNames.kotlinTypeOf,
                        parameter.type.toTypeName(function.typeParameterResolver),
                        MemberNames.emptyList,
                        parameter.hasDefault,
                        MemberNames.emptyList,
                    )
                }
            }
            .add("\n)")
            .build()
    }

    private fun createGetCallableFunction(service: QueryServiceModel): FunSpec {
        return FunSpec.builder("getCallable")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("name", String::class)
            .returns(ClassNames.queryCallable.parameterizedBy(service.serviceClassName).copy(nullable = true))
            .addStatement("return callables[name]")
            .build()
    }

    private fun createCreateInstanceFunction(service: QueryServiceModel): FunSpec {
        return FunSpec.builder("createInstance")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("instanceId", String::class)
            .addParameter("json", ClassNames.json)
            .addParameter("transport", ClassNames.queryTransport)
            .returns(service.serviceClassName)
            .addStatement("return %T(instanceId, json, transport, this)", service.clientImplClassName)
            .build()
    }

    private fun createClientType(service: QueryServiceModel): TypeSpec {
        return TypeSpec.classBuilder(service.clientImplClassName)
            .addOriginatingKSFile(service.containingFile)
            .addModifiers(KModifier.INTERNAL)
            .addSuperinterface(service.serviceClassName)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(INSTANCE_ID_NAME, String::class)
                    .addParameter(JSON_NAME, ClassNames.json)
                    .addParameter(TRANSPORT_NAME, ClassNames.queryTransport)
                    .addParameter(DESCRIPTOR_NAME, service.descriptorClassName)
                    .build()
            )
            .addProperty(
                PropertySpec.builder(INSTANCE_ID_NAME, String::class)
                    .initializer(INSTANCE_ID_NAME).addModifiers(KModifier.PRIVATE).build()
            )
            .addProperty(
                PropertySpec.builder(JSON_NAME, ClassNames.json)
                    .initializer(JSON_NAME).addModifiers(KModifier.PRIVATE).build()
            )
            .addProperty(
                PropertySpec.builder(TRANSPORT_NAME, ClassNames.queryTransport)
                    .initializer(TRANSPORT_NAME).addModifiers(KModifier.PRIVATE).build()
            )
            .addProperty(
                PropertySpec.builder(DESCRIPTOR_NAME, service.descriptorClassName)
                    .initializer(DESCRIPTOR_NAME).addModifiers(KModifier.PRIVATE).build()
            )
            .addProperty(
                PropertySpec.builder(SERIALIZER_CACHE_NAME, ClassNames.querySerializerCache)
                    .addModifiers(KModifier.PRIVATE)
                    .initializer("%T()", ClassNames.querySerializerCache)
                    .build()
            )
            .addProperty(
                PropertySpec.builder(EMPTY_ARRAY_NAME, Types.anyNullableArray)
                    .addModifiers(KModifier.PRIVATE)
                    .initializer("%M()", MemberNames.emptyArray)
                    .build()
            )
            .apply {
                service.functions.forEach { function -> addFunction(createQueryFunction(function)) }
            }
            .build()
    }

    private fun createQueryFunction(function: QueryFunctionModel): FunSpec {
        val returnTypeName = function.returnType.toTypeName(function.typeParameterResolver)

        return FunSpec.builder(function.name)
            .addAnnotation(
                AnnotationSpec.builder(Suppress::class).addMember("%S", "UNCHECKED_CAST").build()
            )
            .addModifiers(KModifier.OVERRIDE, KModifier.SUSPEND)
            .addParameters(
                function.parameters.map { parameter ->
                    ParameterSpec.builder(
                        parameter.name?.asString() ?: error("parameter name is null"),
                        parameter.type.toTypeName(function.typeParameterResolver),
                    ).build()
                }
            )
            .returns(returnTypeName)
            .addCode(
                CodeBlock.builder()
                    .addStatement("val callable = %L.getCallable(%S)!!", DESCRIPTOR_NAME, function.name)
                    .addStatement(
                        "val arguments: %T = %L",
                        Types.anyNullableArray,
                        createArgumentsArray(function),
                    )
                    .addStatement(
                        "val argsSerializer = %L.getParameterSerializer(callable, %L.serializersModule)",
                        SERIALIZER_CACHE_NAME, JSON_NAME
                    )
                    .addStatement(
                        "val payload = %L.encodeToString(argsSerializer, arguments)",
                        JSON_NAME
                    )
                    .addStatement(
                        "val frame = %T(\n" +
                                "    contract = %L.fqName,\n" +
                                "    callable = %S,\n" +
                                "    correlationId = java.util.UUID.randomUUID().toString(),\n" +
                                "    originInstanceId = %L,\n" +
                                "    payload = payload\n" +
                                ")",
                        ClassNames.queryFrame, DESCRIPTOR_NAME, function.name, INSTANCE_ID_NAME
                    )
                    .addStatement(
                        "val resultPayload = %L.ask(frame, %L.timeoutMillis) ?: return null",
                        TRANSPORT_NAME, DESCRIPTOR_NAME
                    )
                    .addStatement(
                        "val returnSerializer = %L.getReturnTypeSerializer(callable, %L.serializersModule)",
                        SERIALIZER_CACHE_NAME, JSON_NAME
                    )
                    .addStatement(
                        "return %L.decodeFromString(returnSerializer, resultPayload) as %T",
                        JSON_NAME, returnTypeName
                    )
                    .build()
            )
            .build()
    }

    private fun createArgumentsArray(function: QueryFunctionModel): CodeBlock {
        if (function.parameters.isEmpty()) {
            return CodeBlock.of("%L", EMPTY_ARRAY_NAME)
        }

        return CodeBlock.builder()
            .add("%M(", MemberNames.arrayOf)
            .apply {
                function.parameters.forEachIndexed { index, parameter ->
                    if (index > 0) add(", ")
                    add("%N", parameter.name?.asString() ?: error("parameter name is null"))
                }
            }
            .add(")")
            .build()
    }
}
