package dev.slne.surf.eventbus.service

import dev.slne.surf.eventbus.InternalEventBusApi

/** One method of a `@QueryService` or `@RpcService` contract, generated by the KSP processor. */
@InternalEventBusApi
interface ServiceCallable<Service : Any> {
    val name: String
    val returnType: ServiceType
    val invoker: ServiceInvoker<Service>
    val parameters: Array<out ServiceParameter>

    /**
     * Whether this call is `@FireAndForget`: no reply is sent or awaited.
     *
     * Always `false` for a query — the processor rejects `@FireAndForget` there, because a
     * question without an answer is an event.
     */
    val fireAndForget: Boolean
}
