package dev.slne.surf.rabbitmq.processor.rpc.codegen

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import dev.slne.surf.rabbitmq.processor.ClassNames
import dev.slne.surf.rabbitmq.processor.MemberNames
import dev.slne.surf.rabbitmq.processor.Types
import dev.slne.surf.rabbitmq.processor.rpc.model.RpcFunctionModel
import dev.slne.surf.rabbitmq.processor.rpc.model.RpcServiceModel

class RpcClientImplCodegen(
    private val logger: KSPLogger,
    private val codeGenerator: CodeGenerator
) {

    companion object {
        private const val SERVICE_ID_NAME = "__serviceId__"
        private const val API_NAME = "__api__"
        private const val DESCRIPTOR_NAME = "__descriptor__"
        private const val EMPTY_ARRAY_NAME = "__emptyArray__"
    }

    fun generate(service: RpcServiceModel) {
        val clientType = TypeSpec.classBuilder(service.clientImplClassName)
            .addInternalDeprecation()
            .addModifiers(KModifier.INTERNAL)
            .addSuperinterface(service.serviceClassName)
            .primaryConstructor(createConstructor(service))
            .addProperty(createServiceIdProperty())
            .addProperty(createApiProperty())
            .addProperty(createDescriptorProperty(service))
            .addProperty(createEmptyArrayProperty())
            .apply {
                service.functions.forEach { function ->
                    addFunction(createRpcFunction(function))
                }
            }
            .build()

        FileSpec.builder(service.clientImplClassName)
            .addFileComment("Code generated by Surf RabbitMQ. DO NOT EDIT!")
            .optInInternalRabbitApi()
            .suppressInternalDeprecation()
            .indent("    ")
            .addType(clientType)
            .build()
            .writeTo(codeGenerator, aggregating = true)
    }

    private fun createConstructor(service: RpcServiceModel): FunSpec {
        return FunSpec.constructorBuilder()
            .addParameter(SERVICE_ID_NAME, Long::class)
            .addParameter(API_NAME, ClassNames.rabbitMqApi)
            .addParameter(DESCRIPTOR_NAME, service.descriptorClassName)
            .build()
    }

    private fun createServiceIdProperty(): PropertySpec {
        return PropertySpec.builder(SERVICE_ID_NAME, Long::class)
            .initializer(SERVICE_ID_NAME)
            .addModifiers(KModifier.PRIVATE)
            .build()
    }

    private fun createApiProperty(): PropertySpec {
        return PropertySpec.builder(API_NAME, ClassNames.rabbitMqApi)
            .initializer(API_NAME)
            .addModifiers(KModifier.PRIVATE)
            .build()
    }

    private fun createDescriptorProperty(service: RpcServiceModel): PropertySpec {
        return PropertySpec.builder(DESCRIPTOR_NAME, service.descriptorClassName)
            .initializer(DESCRIPTOR_NAME)
            .addModifiers(KModifier.PRIVATE)
            .build()
    }

    private fun createEmptyArrayProperty(): PropertySpec {
        return PropertySpec.builder(EMPTY_ARRAY_NAME, Types.anyNullableArray)
            .addModifiers(KModifier.PRIVATE)
            .initializer("%M()", MemberNames.emptyArray)
            .build()
    }

    private fun createRpcFunction(
        function: RpcFunctionModel,
    ): FunSpec {
        return FunSpec.builder(function.name)
            .addModifiers(KModifier.OVERRIDE, KModifier.SUSPEND)
            .addParameters(createFunctionParameters(function))
            .returns(function.returnType.toTypeName(function.typeParameterResolver))
            .addCode(createRpcFunctionBody(function))
            .build()
    }

    private fun createFunctionParameters(function: RpcFunctionModel): List<ParameterSpec> {
        return function.parameters.mapNotNull { parameter ->
            val name = parameter.name?.asString()
            if (name == null) {
                logger.error("Cannot generate function ${function.name}: parameter name is null", parameter)
                return@mapNotNull null
            }

            ParameterSpec.builder(
                name = name,
                type = parameter.type.toTypeName(function.typeParameterResolver),
            ).build()
        }
    }

    private fun createRpcFunctionBody(
        function: RpcFunctionModel,
    ): CodeBlock {
        return CodeBlock.builder()
            .add("return %L.rpcService.call(\n", API_NAME)
            .withIndent {
                add("%L\n", createRabbitRpcCall(function))
            }
            .add(")")
            .build()
    }

    private fun createRabbitRpcCall(
        function: RpcFunctionModel,
    ): CodeBlock {
        return CodeBlock.builder()
            .add("%T(\n", ClassNames.rpcRabbitCall)
            .withIndent {
                add("descriptor = %L,\n", DESCRIPTOR_NAME)
                add("callableName = %S,\n", function.name)
                add("serviceId = %L,\n", SERVICE_ID_NAME)
                add("arguments = %L\n", createArgumentsArray(function))
            }
            .add(")")
            .build()
    }

    private fun createArgumentsArray(function: RpcFunctionModel): CodeBlock {
        if (function.parameters.isEmpty()) {
            return CodeBlock.of("%L", EMPTY_ARRAY_NAME)
        }

        return CodeBlock.builder()
            .add("%M(\n", MemberNames.arrayOf)
            .withIndent {
                function.parameters.forEachIndexed { index, parameter ->
                    if (index > 0) add(",\n")
                    val parameterName = parameter.name?.asString()
                        ?: error("Cannot generate function ${function.name}: parameter name is null")

                    add("%N", parameterName)
                }
                add("\n")
            }
            .add(")")
            .build()
    }
}