package dev.slne.surf.rabbitmq.processor.rpc.codegen

import com.google.devtools.ksp.processing.CodeGenerator
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.addOriginatingKSFile
import com.squareup.kotlinpoet.ksp.writeTo
import dev.slne.surf.rabbitmq.processor.ClassNames
import dev.slne.surf.rabbitmq.processor.rpc.model.RpcServiceModel

class RpcDescriptorCodegen(private val codeGenerator: CodeGenerator) {
    private val invokerCodegen = RpcInvokerCodegen()
    private val callableCodegen = RpcCallableCodegen()

    fun generate(service: RpcServiceModel) {
        val descriptorType = TypeSpec.objectBuilder(service.descriptorClassName)
            .addOriginatingKSFile(service.containingFile)
            .addInternalDeprecation()
            .addModifiers(KModifier.INTERNAL)
            .addSuperinterface(ClassNames.rpcServiceDescriptor.parameterizedBy(service.serviceClassName))
            .addProperty(
                PropertySpec.builder("simpleName", String::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%S", service.simpleName)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("fqName", String::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%S", service.fqName)
                    .build()
            )
            .apply {
                service.functions.forEach { function ->
                    addProperty(invokerCodegen.createInvokerProperty(service, function))
                }

                addProperty(callableCodegen.createCallablesProperty(service))

                service.functions.forEach { function ->
                    addFunction(invokerCodegen.createInvokerFunction(service, function))
                }

                addFunction(callableCodegen.createCallablesFunction(service))
                addFunction(createGetCallableFunction(service))
                addFunction(createCreateInstanceFunction(service))
            }
            .build()

        FileSpec.builder(service.packageName, service.descriptorClassName.simpleName)
            .addFileComment("Code generated by Surf RabbitMQ. DO NOT EDIT!")
            .optInInternalRabbitApi()
            .suppressInternalDeprecation()
            .indent("    ")
            .addType(descriptorType)
            .build()
            .writeTo(codeGenerator, aggregating = false)
    }

    private fun createGetCallableFunction(service: RpcServiceModel): FunSpec {
        return FunSpec.builder("getCallable")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("name", String::class)
            .returns(
                ClassNames.rpcCallable
                    .parameterizedBy(service.serviceClassName)
                    .copy(nullable = true)
            )
            .addStatement("return callables[name]")
            .build()
    }

    private fun createCreateInstanceFunction(service: RpcServiceModel): FunSpec {
        return FunSpec.builder("createInstance")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("serviceId", Long::class)
            .addParameter("api", ClassNames.rabbitMqApi)
            .returns(service.serviceClassName)
            .addStatement("return %T(serviceId, api, this)", service.clientImplClassName)
            .build()
    }
}