package dev.slne.surf.eventbus.query.callable

import dev.slne.surf.eventbus.InternalEventBusApi
import kotlin.reflect.KType

/** One method of a `@QueryService` contract, generated by the KSP processor. */
@InternalEventBusApi
interface QueryCallable<Service : Any> {
    val name: String
    val returnType: KType
    val invoker: QueryInvoker<Service>
    val parameters: Array<out QueryParameter>
}
