package dev.slne.surf.eventbus.ksp.codegen

import com.google.devtools.ksp.processing.CodeGenerator
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.addOriginatingKSFile
import com.squareup.kotlinpoet.ksp.writeTo
import dev.slne.surf.eventbus.ksp.model.ServiceModel

/** Generates `<Name>Descriptor` for a `@QueryService` contract. */
class QueryDescriptorCodegen(private val codeGenerator: CodeGenerator) {
    private val invokerCodegen = InvokerCodegen()
    private val callableCodegen = CallableCodegen()
    private val clientCodegen = QueryClientCodegen()

    fun generate(service: ServiceModel) {
        val descriptorType = TypeSpec.objectBuilder(service.descriptorClassName)
            .addOriginatingKSFile(service.containingFile)
            .addModifiers(KModifier.INTERNAL)
            .addSuperinterface(ClassNames.queryServiceDescriptor.parameterizedBy(service.serviceClassName))
            .addProperty(
                PropertySpec.builder("simpleName", String::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%S", service.simpleName)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("fqName", String::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%S", service.fqName)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("timeoutMillis", Long::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%LL", service.timeoutMillis)
                    .build()
            )
            .apply {
                service.functions.forEach { function ->
                    addProperty(invokerCodegen.createInvokerProperty(service, function))
                }

                addProperty(callableCodegen.createCallablesProperty(service))

                service.functions.forEach { function ->
                    addFunction(invokerCodegen.createInvokerFunction(service, function))
                }

                addFunction(callableCodegen.createCallablesFunction(service))
                addFunction(callableCodegen.createGetCallableFunction(service))
                addFunction(createCreateInstanceFunction(service))
            }
            .build()

        FileSpec.builder(service.packageName, service.descriptorClassName.simpleName)
            .addFileComment("Code generated by Surf EventBus. DO NOT EDIT!")
            .optInInternalEventBusApi()
            .indent("    ")
            .addType(descriptorType)
            .addType(clientCodegen.createClientType(service))
            .build()
            .writeTo(codeGenerator, aggregating = false)
    }

    private fun createCreateInstanceFunction(service: ServiceModel): FunSpec {
        return FunSpec.builder("createInstance")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("instanceId", String::class)
            .addParameter("json", ClassNames.json)
            .addParameter("transport", ClassNames.queryTransport)
            .returns(service.serviceClassName)
            .addStatement("return %T(instanceId, json, transport, this)", service.clientImplClassName)
            .build()
    }
}
